name:                christopher
version:             0.1.0.0
github:              "archambaultv/christopher"
license:             MIT
author:              "Vincent Archambault-B"
maintainer:          "vincentarchambault@icloud.com"
copyright:           "Vincent Archambault"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Financial planning
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/archambaultv/christopher#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- recursion-schemes
- Decimal
- cassava
- bytestring
- scientific
- time
- aeson
- yaml
- filepath
- optparse-applicative
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  christopher:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - christopher

tests:
  christopher-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - christopher
